SMAC/config/routes.rb
Rails.application.routes.draw do

  get 'main/index'

  get 'bands/new'

  get 'bands/list'

  get 'genres/new'

  get 'artists/new'

  get 'release_types/new'

  get 'releases/new'

  # defines the objects that we have
  resources :bands do
    # this is a nested object inside an object
    resources :weblinks
  end

  resources :genres

  resources :artists

  resources :release_types

  resources :releases

  root 'main#index'

end

SMAC/app/models/genre.rb
class Genre < ApplicationRecord

  # this is a many to many relationship between band and genre through the table band_genres
  has_many :band_genres
  has_many :bands, :through => :band_genres

  # the fields below must always be filled in a form
  validates :name, presence: true

end

SMAC/app/controllers/genres_controller.rb
class GenresController < ApplicationController

  # finds all the genres in the database
  # renders the index view by default
  def index
    @genres = Genre.all
  end

  # this will find the requested object
  # renders the show view by default
  def show
    @genre = Genre.find(params[:id])
  end

  # this will create an empty genre object
  # renders the new view by default
  def new
    @genre = Genre.new
  end

  # this will find the requested object
  # renders the edit view by default
  def edit
    @genre = Genre.find(params[:id])
  end

  # this takes the object created in `new` and tries to save it to the database
  def create
    @genre = Genre.new(genre_params)
    # validate the data that has been passed, this is linked to the objects model where the required fields are defined
    if @genre.save
      redirect_to genres_path
    else
      # overwrite the default render
      render 'new'
    end
  end

  # this tries to update the selected object in the database
  def update
    @genre = Genre.find(params[:id])
    # validate the data that has been passed, this is linked to the objects model where the required fields are defined
    if @genre.update(genre_params)
      redirect_to edit_genre_path(@genre)
    else
      # overwrite the default render
      render 'edit'
    end
  end

  # this will remove the selected object from the database
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    redirect_to genres_path
  end

  private
    # define the objects parameters here to unclutter the code
    def genre_params
      params.require(:genre).permit(:name)
    end

end

SMAC/app/helpers/genres_helper.rb
module GenresHelper
end

SMAC/app/views/genres/_genre.html.erb
<%= form_with model: @genre, local: true do |form| %>
   
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:
      </h2>
    <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <h2> Genre </h2>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

SMAC/app/views/genres/edit.html.erb
<%= render 'genre' %>

<hr>

<%= link_to 'Cancel', genres_path %>

SMAC/app/views/genres/index.html.erb
<h1> Genres </h1>

<table>
  <tr>
    <th> Name </th>
  </tr>

  <% @genres.each do |genre| %>
    <tr>
      <td> <%= genre.name %> </td>
      <td> | <%= link_to 'Edit', edit_genre_path(genre) %> | </td>
      <td> <%= link_to 'Delete', genre_path(genre), method: :delete, data: { confirm: 'Are you sure you want to remove this record?' } %> </td>
    </tr>
  <% end %>

</table>

<hr>

<%= link_to "Index", main_index_path %>

SMAC/app/views/genres/new.html.erb
<%= render 'genre' %>

<hr>

<%= link_to 'Cancel', main_index_path %>