SMAC/config/routes.rb
Rails.application.routes.draw do

  get 'main/index'

  get 'bands/new'

  get 'bands/list'

  get 'genres/new'

  get 'artists/new'

  get 'release_types/new'

  get 'releases/new'

  # defines the objects that we have
  resources :bands do
    # this is a nested object inside an object
    resources :weblinks
  end

  resources :genres

  resources :artists

  resources :release_types

  resources :releases

  root 'main#index'

end

SMAC/app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    # renders the index view by default
  end

end

SMAC/app/helpers/main_helper.rb
module MainHelper
end

SMAC/app/views/main/_menu.html.erb
<div class="menu">

  <div>
    <%= link_to main_index_path do %>
      <%= image_tag("menu_logo.png", alt: "SMAC") %>
    <% end %>
  </div

  <ul>
    <li class="menu_item"> <%= link_to "Bands", bands_path %> </li>
      <ul>
        <li class="menu_item"> <%= link_to "Submit a band", bands_new_path %> </li>
      </ul>
    <li class="menu_item"> <%= link_to "Artists", artists_path %> </li>
      <ul>
        <li class="menu_item"> <%= link_to "Submit an artist", artists_new_path %> </li>
      </ul>
    <li class="menu_item"> <%= link_to "Releases", releases_path %> </li>
      <ul>
        <li class="menu_item"> <%= link_to "Submit a release", releases_new_path %> </li>
      </ul>
    <li class="menu_item"> <%= link_to "Genres", genres_path %> </li>
      <ul>
        <li class="menu_item"> <%= link_to "Submit a genre", genres_new_path %> </li>
      </ul>
    <li class="menu_item"> <%= link_to "Release types", release_types_path %> </li>
      <ul>
        <li class="menu_item"> <%= link_to "Submit a release type", release_types_new_path %> </li>
      </ul>
  </ul>

</div>

SMAC/app/views/main/index.html.erb
<%= render 'menu' %>

<div class="base">

  <h1> Scuffed Metal Archives Clone </h1>

  <p> Welcome, things will be added here over time. </p>

  <p> Now with css and bootstrap! Yay! </p>

</div>