SMAC/config/routes.rb
Rails.application.routes.draw do

  get 'main/index'

  get 'bands/new'

  get 'bands/list'

  get 'genres/new'

  get 'artists/new'

  get 'release_types/new'

  get 'releases/new'

  # defines the objects that we have
  resources :bands do
    # this is a nested object inside an object
    resources :weblinks
  end

  resources :genres

  resources :artists

  resources :release_types

  resources :releases

  root 'main#index'

end

SMAC/app/models/band.rb
class Band < ApplicationRecord

  # a band can have many weblinks
  # when a band gets destroyed, all its weblinks get destroyed too
  has_many :weblinks, dependent: :destroy

  # this is a many to many relationship between band and artist through the table band_artists
  has_many :band_artists
  has_many :artists, :through => :band_artists

  # this is a many to many relationship between band and genre through the table band_genres
  has_many :band_genres
  has_many :genres, :through => :band_genres

  # this is a one to many relationship between band and releasesm, a band can have X releases
  has_many :releases, dependent: :destroy

  # a band can have multiple band pictures, this is part of the ActiveStorage
  has_many_attached :band_pictures

  # a band can have multiple band logos, this is part of the ActiveStorage
  has_many_attached :band_logos

  # the fields below must always be filled in a form
  validates :name, presence: true
  validates :country, presence: true
  validates :location, presence: true
  validates :formation_date, presence: true

end

SMAC/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  # finds all the bands in the database
  # renders the index view by default
  def index
    @bands = Band.all
  end

  # this will find the requested object
  # renders the show view by default
  def show
    @band = Band.find(params[:id])
  end

  # this will create an empty band object
  # renders the new view by default
  def new
    @band = Band.new
  end

  def list
    @bands = Band.where('substr(name, 1, 1) = ?', params[:letter])
  end

  # this will find the requested object
  # renders the edit view by default
  def edit
    @band = Band.find(params[:id])
  end

  # this takes the object created in `new` and tries to save it to the database
  def create
    @band = Band.new(band_params)
    # validate the data that has been passed, this is linked to the objects model where the required fields are defined
    if @band.save
      redirect_to edit_band_path(@band)
    else
      # overwrite the default render
      render 'new'
    end
  end

  # this tries to update the selected object in the database
  def update
    @band = Band.find(params[:id])
    # validate the data that has been passed, this is linked to the objects model where the required fields are defined
    if @band.update(band_params)
      redirect_to edit_band_path(@band)
    else
      # overwrite the default render
      render 'edit'
    end
  end

  # this will remove the selected object from the database
  def destroy
    @band = Band.find(params[:id])
    @band.destroy

    redirect_to bands_path
  end

  private
		# define the objects parameters here to unclutter the code, the [] parameters are outside of this object but belong to it
    def band_params
      params.require(:band).permit(:name, :country, :location, :formation_date, band_pictures: [], band_logos: [], genre_ids: [], artist_ids: [])
    end

end

SMAC/app/helpers/bands_helper.rb
module BandsHelper
end

SMAC/app/views/bands/_alpha_bar.html.erb
<ul class="alpha_search_bar">
  <li> <a> <%= link_to "A", bands_list_path(:letter => "A") %> </a> </li>
  <li> <a> <%= link_to "B", bands_list_path(:letter => "B") %> </a> </li>
  <li> <a> <%= link_to "C", bands_list_path(:letter => "C") %> </a> </li>
  <li> <a> <%= link_to "D", bands_list_path(:letter => "D") %> </a> </li>
  <li> <a> <%= link_to "E", bands_list_path(:letter => "E") %> </a> </li>
  <li> <a> <%= link_to "F", bands_list_path(:letter => "F") %> </a> </li>
  <li> <a> <%= link_to "G", bands_list_path(:letter => "G") %> </a> </li>
  <li> <a> <%= link_to "H", bands_list_path(:letter => "H") %> </a> </li>
  <li> <a> <%= link_to "I", bands_list_path(:letter => "I") %> </a> </li>
  <li> <a> <%= link_to "J", bands_list_path(:letter => "J") %> </a> </li>
  <li> <a> <%= link_to "K", bands_list_path(:letter => "K") %> </a> </li>
  <li> <a> <%= link_to "L", bands_list_path(:letter => "L") %> </a> </li>
  <li> <a> <%= link_to "M", bands_list_path(:letter => "M") %> </a> </li>
  <li> <a> <%= link_to "N", bands_list_path(:letter => "N") %> </a> </li>
  <li> <a> <%= link_to "O", bands_list_path(:letter => "O") %> </a> </li>
  <li> <a> <%= link_to "P", bands_list_path(:letter => "P") %> </a> </li>
  <li> <a> <%= link_to "Q", bands_list_path(:letter => "Q") %> </a> </li>
  <li> <a> <%= link_to "R", bands_list_path(:letter => "R") %> </a> </li>
  <li> <a> <%= link_to "S", bands_list_path(:letter => "S") %> </a> </li>
  <li> <a> <%= link_to "T", bands_list_path(:letter => "T") %> </a> </li>
  <li> <a> <%= link_to "U", bands_list_path(:letter => "U") %> </a> </li>
  <li> <a> <%= link_to "V", bands_list_path(:letter => "V") %> </a> </li>
  <li> <a> <%= link_to "W", bands_list_path(:letter => "W") %> </a> </li>
  <li> <a> <%= link_to "X", bands_list_path(:letter => "X") %> </a> </li>
  <li> <a> <%= link_to "Y", bands_list_path(:letter => "Y") %> </a> </li>
  <li> <a> <%= link_to "Z", bands_list_path(:letter => "Z") %> </a> </li>
</ul>

<br>

SMAC/app/views/bands/_alpha_search.html.erb
<div class="base">

  <%= render 'alpha_bar' %>

  <%= render 'band_list' %>

</div>

SMAC/app/views/bands/_band_list.html.erb
<table class="table table-striped table-bordered table-hover table-dark">
  <thead class="thead-dark">
    <tr>
      <th scope="col"> Band </th>
      <th scope="col"> Country </th>
      <th scope="col"> Genre(s) </th>
    </tr>
  </thead>
  <% @bands.each do |band| %>
    <tbody>
      <tr>
        <th scope="row"> <%= link_to band.name, band_path(band) %> </th>
        <td> <%= band.country %> </td>
        <td> 
          <% band.genres.each do |genre| %>
            <%= genre.name %> /
          <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

SMAC/app/views/bands/_form.html.erb
<%= form_with model: @band, local: true do |form| %>
   
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:
      </h2>
    <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>
   
  <h2> Band </h2>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :country %><br>
    <%= form.text_field :country %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </p>

  <p>
    <%= form.label :formation_date %><br>
    <%= form.date_field :formation_date %>
  </p>

  <h2> Band Picture(s) </h2>

  <p>
    <%= form.file_field :band_pictures, multiple: true %>
  </p>

  <h2> Band Logo(s) </h2>

  <p>
    <%= form.file_field :band_logos, multiple: true %>
  </p> 
    
  <h2> Genre(s) </h2>

  <p>
    <%= form.collection_check_boxes :genre_ids, Genre.all, :id, :name, include_blank: true %>
  </p>

  <h2> Artist(s) </h2>

  <p>
    <%= form.collection_check_boxes :artist_ids, Artist.all, :id, :alias, include_blank: true %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

SMAC/app/views/bands/_picture_view.html.erb
<div class="picture_view">

  <!-- "only show the `latest` band logo" --!>
  <p>
    <%= if not @band.band_logos.last.blank?
      image_tag @band.band_logos.last, style: 'height:100%; width:100%;'
    end %>
  </p>

  <!-- "only show the `latest` band picture" --!>
  <p>
    <%= if not @band.band_pictures.last.blank?
      image_tag @band.band_pictures.last, style: 'height:100%; width:100%;'
    end %>
  </p>

</div>

SMAC/app/views/bands/edit.html.erb
<%= render 'form' %>

<hr>

<%= link_to 'Cancel', bands_path %>

SMAC/app/views/bands/index.html.erb
<%= render 'main/menu' %>

<div class="base">

  <br>

  <h3> Browse Bands - Alphabetically </h3>

  <br>

  <%= render 'alpha_bar' %>

  <%= render 'band_list' %>

</div>

SMAC/app/views/bands/list.html.erb
<%= render 'main/menu' %>

<%= render 'alpha_search' %>

SMAC/app/views/bands/new.html.erb
<%= render 'form' %>

<hr>

<%= link_to 'Cancel', main_index_path %>

SMAC/app/views/bands/show.html.erb
<%= render "main/menu" %>
<%= render "picture_view" %>

<div class="base">

  <br>

  <h1> <%= @band.name %> </h1>
 
  <br>

  <div class="band_view_left_1">
    <p> Country of origin: </p>
    <p> Location: </p>
    <p> Formed in: </p>
  </div>

  <div class="band_view_right_1">
    <p> <%= @band.country %> </p>
    <p> <%= @band.location %> </p>
    <p> <%= @band.formation_date %> </p>
  </div>

  <div class="band_view_left_2">
    <p> Genre: </p>
  </div>

  <div class="band_view_right_2">
    <p>
      <% @band.genres.each do |genre| %>
        <%= genre.name %> /
      <% end %>
    </p>
  </div>
  
  <div class="band_view_info">

    <ul class="nav-tabs nav">
      <li class="nav-item">
        <a href="#disco" data-toggle="tab" class="active nav-link">Discography</a>
      </li>
      <li class="nav-item">
        <a href="#members" data-toggle="tab" class="nav-link">Members</a>
      </li>
      <li class="nav-item">
        <a href="#links" data-toggle="tab" class="nav-link">Related Links</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="disco" role="tabpanel" class="tab-pane active container">
        <table>
          <tr>
            <th> Title </th>
            <th> Type </th>
            <th> Year </th>
          </tr>
          <% @band.releases.each do |release| %>
            <tr>
              <td> <%= link_to release.title, release_path(release) %> </td>
              <td> <%= ReleaseType.find_by(id: release.release_type_id).name %> </td>
              <td> <%= release.release_date %> </td>
            </tr>
          <% end %>
         </table>
      </div>
      <div id="members" role="tabpanel" class="tab-pane container">
        <p> I think i need JavaScript here... no clue how :D </p>
        <p>
          <% @band.artists.each do |artist| %>
            <%= link_to artist.alias, artist_path(artist) %>
          <% end %>
        </p>
      </div>
      <div id="links" role="tabpanel" class="tab-pane container">
        <p> I think i need JavaScript here... no clue how :D </p>
        <table>
          <tr>
            <th> Title </th>
            <th> URL </th>
            <th> Ref </th>
            <th> Action(s) </th>
          </tr>
          <% @band.weblinks.each do |weblink| %>
            <tr>
              <td> <%= weblink.title %> </td>
              <td> <%= weblink.url %> </td>
              <td> <a href= <%= weblink.url %> > <%= weblink.title %> </a> </td> 
            </tr>
          <% end %>
        </table>
      </div>
    </div>

  </div>

</div>