SMAC/config/routes.rb
Rails.application.routes.draw do

  get 'main/index'

  get 'bands/new'

  get 'bands/list'

  get 'genres/new'

  get 'artists/new'

  get 'release_types/new'

  get 'releases/new'

  # defines the objects that we have
  resources :bands do
    # this is a nested object inside an object
    resources :weblinks
  end

  resources :genres

  resources :artists

  resources :release_types

  resources :releases

  root 'main#index'

end

SMAC/app/controllers/release_types_controller.rb
class ReleaseTypesController < ApplicationController

  # finds all the release types in the database
  # renders the index view by default
  def index
    @releaseTypes = ReleaseType.all
  end

  # this will find the requested object
  # renders the show view by default
  def show
    @releaseType = ReleaseType.find(params[:id])
  end

  # this will create an empty release type object
  # renders the new view by default
  def new
    @releaseType = ReleaseType.new
  end

  # this will find the requested object
  # renders the edit view by default
  def edit
    @releaseType = ReleaseType.find(params[:id])
  end

  # this takes the object created in `new` and tries to save it to the database
  def create
    @releaseType = ReleaseType.new(release_type_params)
    # validate the data that has been passed, this is linked to the objects model where the required fields are defined
    if @releaseType.save
      redirect_to release_types_path
    else
      # overwrite the default render
      render 'new'
    end
  end

  # this tries to update the selected object in the database
  def update
    @releaseType = ReleaseType.find(params[:id])
    # validate the data that has been passed, this is linked to the objects model where the required fields are defined
    if @releaseType.update(release_type_params)
      redirect_to edit_release_type_path(@releaseType)
    else
      # overwrite the default render
      render 'edit'
    end
  end

  # this will remove the selected object from the database
  def destroy
    @releaseType = ReleaseType.find(params[:id])
    @releaseType.destroy

    redirect_to release_types_path
  end

  private
    # define the objects parameters here to unclutter the code
    def release_type_params
      params.require(:release_type).permit(:name)
    end

end

SMAC/app/helpers/release_types_helper.rb
module ReleaseTypesHelper
end

SMAC/app/views/release_types/_type.html.erb
<%= form_with model: @releaseType, local: true do |form| %>
   
  <% if @releaseType.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@releaseType.errors.count, "error") %> prohibited this release type from being saved:
      </h2>
    <ul>
      <% @releaseType.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <h2> Release Type </h2>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

SMAC/app/views/release_types/edit.html.erb
<%= render 'type' %>

<hr>

<%= link_to 'Cancel', release_types_path %>

SMAC/app/views/release_types/index.html.erb
<h1> Release Types </h1>

<table>
  <tr>
    <th> Name </th>
  </tr>

  <% @releaseTypes.each do |releaseType| %>
    <tr>
      <td> <%= releaseType.name %> </td>
      <td> | <%= link_to 'Edit', edit_release_type_path(releaseType) %> | </td>
      <td> <%= link_to 'Delete', release_type_path(releaseType), method: :delete, data: { confirm: 'Are you sure you want to remove this record?' } %> </td>
    </tr>
  <% end %>

</table>

<hr>

<%= link_to "Index", main_index_path %>

SMAC/app/views/release_types/new.html.erb
<%= render 'type' %>

<hr>

<%= link_to 'Cancel', main_index_path %>